version: '3.9'
services:
  nest.example:
    container_name: nest.example
    image: nest.example/app
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
    networks:
      - nest-example
    depends_on:
      - pgsql-15

  pgsql-15:
    container_name: pgsql-15
    image: 'postgres:15'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DATABASE_PASSWORD:-secret}'
      POSTGRES_DB: '${DATABASE_NAME}'
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD:-secret}'
    env_file:
      - .env
    volumes:
      - nest-pgsql-15:/var/lib/postgresql/data
    networks:
      - nest-example
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-q',
          '-d',
          '${DATABASE_NAME}',
          '-U',
          '${DATABASE_USERNAME}',
        ]
      retries: 3
      timeout: 5s

networks:
  nest-example:
    driver: bridge

volumes:
  nest-pgsql-15:
